export { default as Home } from "./home"
export { default as About } from "./about"
export { default as Shop } from "./shop"
export { default as Sale } from "./sale"
export { default as SingleBlogDetails } from "./singleBlogDetails"
export { default as Contact } from "./contact"
export { default as PageNotFound } from "./NotFoundPage"
export { default as Cart } from "./cart"