export { default as Home } from "./home"
export { default as About } from "./about"
export { default as Products } from "./products"
export { default as SingleProductDetails } from "./singleProductDetails"
export { default as Contact } from "./contact"
export { default as PageNotFound } from "./NotFoundPage"
export { default as Cart } from "./cart"